### ISSUE TITLE
error in build for rpi4

### ISSUE THREAD

**Issue by alemig97** [raspberry-vanilla/android_kernel_manifest#11] opened 2024-05-09 12:45 UTC
hi Konsta, after modifying some configurations from "make menuconfig", the make works but I can't build the new configuration. I have this error:

 tools/bazel build --config=fast --config=stamp //common:rpi4 --verbose_failures
INFO: Analyzed target //common:rpi4 (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /mnt/BuildDisk/common/BUILD.bazel:1077:13: Creating kernel config (lto=fast;notrim) @//common:rpi4_config failed: (Exit 2): bash failed: error executing KernelConfig command (from target //common:rpi4_config)
  (cd /mnt/BuildDisk/out/bazel/output_user_root/e8f2e35683ca32b00e615875d151af37/execroot/__main__ && \
  exec env - \
  /bin/bash -c '
         # error on failures
           set -e
           set -o pipefail

                export PATH=$(bazel-out/k8-fastbuild/bin/build/kernel/hermetic-tools/readlink -m bazel-out/k8-fastbuild/bin/build/kernel/hermetic-tools)
                # Ensure _setup_env.sh keeps the original items in PATH
                export KLEAF_INTERNAL_BUILDTOOLS_PREBUILT_BIN=bazel-out/k8-fastbuild/bin/build/kernel/hermetic-tools

         # error on failures
           set -e
           set -o pipefail
         # utility functions
           source build/kernel/build_utils.sh
         # source the build environment
           source bazel-out/k8-fastbuild/bin/common/rpi4_env.sh

        # Increase parallelism # TODO(b/192655643): do not use -j anymore
          export MAKEFLAGS="${MAKEFLAGS} -j$(
            make_jobs="$( (while read -r name value; do if [ "$name" = "MAKE_JOBS" ]; then echo "$value"; fi; done < bazel-out/volatile-status.txt) )"
            if [[ -n "$make_jobs" ]]; then
              echo "$make_jobs"
            else
              nproc
            fi
          )"

         # setup LD_LIBRARY_PATH for prebuilts
           export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${ROOT_DIR}/prebuilts/kernel-build-tools/linux-x86/lib64
         # Set up KCONFIG_EXT
           if [ -n "${KCONFIG_EXT}" ]; then
             export KCONFIG_EXT_PREFIX=$(realpath $(dirname ${KCONFIG_EXT}) --relative-to ${ROOT_DIR}/${KERNEL_DIR})/
           fi
           if [ -n "${DTSTREE_MAKEFILE}" ]; then
             export dtstree=$(realpath -s $(dirname ${DTSTREE_MAKEFILE}) --relative-to ${ROOT_DIR}/${KERNEL_DIR})
           fi
         # Set up KCPPFLAGS
         # For Kleaf local (non-sandbox) builds, $ROOT_DIR is under execroot but
         # $ROOT_DIR/$KERNEL_DIR is a symlink to the real source tree under
         # workspace root, making $abs_srctree not under $ROOT_DIR.
           if [[ "$(realpath ${ROOT_DIR}/${KERNEL_DIR})" != "${ROOT_DIR}/${KERNEL_DIR}" ]]; then
             export KCPPFLAGS="$KCPPFLAGS -ffile-prefix-map=$(realpath ${ROOT_DIR}/${KERNEL_DIR})/="
           fi

            KLEAF_CONFIG_TAGS_TMP=$(mktemp kleaf_config_tags.json.XXXXXX)
            # cache_dir_config_tags.py requires --dest to not exist, otherwise it compares
            # and fails.
            rm -f "${KLEAF_CONFIG_TAGS_TMP}"

            # Add label of this target.
            bazel-out/k8-opt-exec-ST-10ba2ffbdcc7/bin/build/kernel/kleaf/impl/cache_dir_config_tags \
                --base bazel-out/k8-fastbuild/bin/common/rpi4_env/common_config_tags.json \
                --target '\''@//common:rpi4_config'\'' \
                --dest "${KLEAF_CONFIG_TAGS_TMP}"

            export OUT_DIR_SUFFIX=$(cat ${KLEAF_CONFIG_TAGS_TMP} | sha1sum -b | cut -c-8)

            export COMMON_OUT_DIR=/mnt/BuildDisk/out/cache/${OUT_DIR_SUFFIX}
            export OUT_DIR=${COMMON_OUT_DIR}/${KERNEL_DIR}
            mkdir -p "${OUT_DIR}"

            # Reconcile differences between expected file and target file, if any,
            # to prevent hash collision.
            bazel-out/k8-opt-exec-ST-10ba2ffbdcc7/bin/build/kernel/kleaf/impl/cache_dir_config_tags \
                --base "${KLEAF_CONFIG_TAGS_TMP}" \
                --dest "${COMMON_OUT_DIR}/kleaf_config_tags.json"

            rm -f "${KLEAF_CONFIG_TAGS_TMP}"
            unset KLEAF_CONFIG_TAGS_TMP

        # Pre-defconfig commands
          eval ${PRE_DEFCONFIG_CMDS}
        # Actual defconfig
          make -C ${KERNEL_DIR} ${TOOL_ARGS} O=${OUT_DIR} ${DEFCONFIG}
        # Post-defconfig commands
          eval ${POST_DEFCONFIG_CMDS}
        # Re-config

        (
            need_olddefconfig=
            configs_to_apply=$(echo $(
        if [[ "$(${KERNEL_DIR}/scripts/config --file ${OUT_DIR}/.config --state LTO_CLANG_FULL)" == "y" ]]; then
            echo "--enable LTO_CLANG"
        fi
    ) $(
        if [[ "$(${KERNEL_DIR}/scripts/config --file ${OUT_DIR}/.config --state LTO_CLANG_FULL)" == "y" ]]; then
            echo "--disable LTO_NONE"
        fi
    ) $(
        if [[ "$(${KERNEL_DIR}/scripts/config --file ${OUT_DIR}/.config --state LTO_CLANG_FULL)" == "y" ]]; then
            echo "--enable LTO_CLANG_THIN"
        fi
    ) $(
        if [[ "$(${KERNEL_DIR}/scripts/config --file ${OUT_DIR}/.config --state LTO_CLANG_FULL)" == "y" ]]; then
            echo "--enable THINLTO"
        fi
    ) $(
        if [[ "$(${KERNEL_DIR}/scripts/config --file ${OUT_DIR}/.config --state LTO_CLANG_FULL)" == "y" ]]; then
            echo "--disable LTO_CLANG_FULL"
        fi
    ))
            # There could be reconfigurations based on configs which can lead to
            #  an empty `configs_to_apply` even when `configs` is not empty,
            #  for that reason it is better to check it is not empty before using it.
            if [ -n "${configs_to_apply}" ]; then
                ${KERNEL_DIR}/scripts/config --file ${OUT_DIR}/.config ${configs_to_apply}
                need_olddefconfig=1
            fi

            if [[ -n "${need_olddefconfig}" ]]; then
                make -C ${KERNEL_DIR} ${TOOL_ARGS} O=${OUT_DIR} olddefconfig
            fi

        )

        # HACK: run syncconfig to avoid re-triggerring kernel_build
          make -C ${KERNEL_DIR} ${TOOL_ARGS} O=${OUT_DIR} syncconfig
        # Grab outputs
          rsync -aL ${OUT_DIR}/.config bazel-out/k8-fastbuild/bin/common/rpi4_config/out_dir/.config
          rsync -aL ${OUT_DIR}/include/ bazel-out/k8-fastbuild/bin/common/rpi4_config/out_dir/include/

        # Ensure reproducibility. The value of the real $ROOT_DIR is replaced in the setup script.
          sed -i'\'''\'' -e '\''s:'\''"${ROOT_DIR}"'\'':${ROOT_DIR}:g'\'' bazel-out/k8-fastbuild/bin/common/rpi4_config/out_dir/include/config/auto.conf.cmd

        # HACK: Ensure we always SYNC auto.conf. This ensures binaries like fixdep are always
        # re-built. See b/263415662
          echo "include/config/auto.conf: FORCE" >> bazel-out/k8-fastbuild/bin/common/rpi4_config/out_dir/include/config/auto.conf.cmd

            ln -sfT ${OUT_DIR_SUFFIX} /mnt/BuildDisk/out/cache/last_config

        ')
# Configuration: 68916f6d1e08a6e521291b026b187b86f07fe8f25844889f1634f06de0586a44
# Execution platform: @local_config_platform//:host
***
*** The source tree is not clean, please run 'make mrproper'
*** in /mnt/BuildDisk/common
***
make[1]: *** [/mnt/BuildDisk/common/Makefile:675: outputmakefile] Error 1
make: *** [Makefile:256: __sub-make] Error 2
Target //common:rpi4 failed to build
INFO: Elapsed time: 3.129s, Critical Path: 1.61s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully

can you help me please?

**Comment by KonstaT** [comment] 2024-05-09 13:25
Duplicate of https://github.com/raspberry-vanilla/android_kernel_manifest/issues/10. No, you're not going to anywhere with `make menuconfig`.

Also the error message tells exactly what's wrong.
```*** The source tree is not clean, please run 'make mrproper'```

**Closed as completed by KonstaT** 2024-05-09 13:25 UTC

**Comment by alemig97** [comment] 2024-05-09 13:29
With the command 'make mrproper', I would delete all the changes made. To change the kernel configuration, can't I use comand 'make menuconfig'? Do I need to change android_rpi4_defconfig for configuration??

**Comment by KonstaT** [comment] 2024-05-09 13:33
https://github.com/raspberry-vanilla/android_kernel_manifest/issues/10#issuecomment-2094091252

**Comment by alemig97** [comment] 2024-05-09 14:15
Thanks, after editing the configuration file I can do the build directly with the command "tools/bazel build --config=fast --config=stamp //common:rpi4"? Apologies for the repeated inconvenience.

**Comment by KonstaT** [comment] 2024-05-09 16:45
Yes, and commit your changes so the kernel isn't tagged as `-dirty`.

If you want to just regenerate the defconfig after changes:
```
tools/bazel build --config=fast --config=stamp //common:rpi4_defconfig
cp bazel-bin/common/rpi4_defconfig/.config common/arch/arm64/configs/android_rpi4_defconfig
```
And again, commit your changes.

**Comment by alemig97** [comment] 2024-06-05 10:14
Hello Konsta, I wanted to make a comparison of the different methods of kernel compression/decompression, and by adding the compression configuration to android_rpi4_defconfig (CONFIG_KERNEL_GZIP), I can't seem to have it on config.gz on Raspberry Pi. Additional the size of image remains the same. How is it possible?
